"""initial migration

Revision ID: 171d9807f230
Revises: 
Create Date: 2021-02-19 15:59:12.139020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '171d9807f230'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('movie',
    sa.Column('MovieID', sa.String(length=30), nullable=False),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.Column('Age', sa.Integer(), nullable=True),
    sa.Column('Description', sa.String(length=500), nullable=True),
    sa.Column('RunningTime', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('MovieID')
    )
    op.create_table('screen',
    sa.Column('ScreenID', sa.Integer(), nullable=False),
    sa.Column('SeatQuantity', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('ScreenID')
    )
    op.create_table('user',
    sa.Column('UserID', sa.Integer(), nullable=False),
    sa.Column('Authenticated', sa.Boolean(), nullable=True),
    sa.Column('Username', sa.String(length=20), nullable=True),
    sa.Column('Password', sa.String(length=20), nullable=True),
    sa.Column('Email', sa.String(length=50), nullable=True),
    sa.Column('Privilage', sa.Integer(), nullable=True),
    sa.PrimaryKeyConstraint('UserID')
    )
    op.create_table('screening',
    sa.Column('ScreeningID', sa.Integer(), nullable=False),
    sa.Column('MovieID', sa.Integer(), nullable=True),
    sa.Column('ScreenID', sa.Integer(), nullable=True),
    sa.Column('StartTimestamp', sa.DateTime(), nullable=True),
    sa.Column('EndTimestamp', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['MovieID'], ['movie.MovieID'], ),
    sa.ForeignKeyConstraint(['ScreenID'], ['screen.ScreenID'], ),
    sa.PrimaryKeyConstraint('ScreeningID')
    )
    op.create_table('seat',
    sa.Column('SeatID', sa.Integer(), nullable=False),
    sa.Column('ScreenID', sa.Integer(), nullable=True),
    sa.Column('Type', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['ScreenID'], ['screen.ScreenID'], ),
    sa.PrimaryKeyConstraint('SeatID')
    )
    op.create_table('booking',
    sa.Column('BookingID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('ScreeningID', sa.Integer(), nullable=True),
    sa.Column('Timestamp', sa.DateTime(), nullable=True),
    sa.Column('TotalPrice', sa.Float(), nullable=True),
    sa.ForeignKeyConstraint(['ScreeningID'], ['screening.ScreeningID'], ),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('BookingID')
    )
    op.create_table('ticket',
    sa.Column('TicketID', sa.Integer(), nullable=False),
    sa.Column('BookingID', sa.Integer(), nullable=True),
    sa.Column('SeatID', sa.Integer(), nullable=True),
    sa.Column('Category', sa.Integer(), nullable=True),
    sa.Column('QR', sa.String(length=4296), nullable=True),
    sa.ForeignKeyConstraint(['BookingID'], ['booking.BookingID'], ),
    sa.ForeignKeyConstraint(['SeatID'], ['seat.SeatID'], ),
    sa.PrimaryKeyConstraint('TicketID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('ticket')
    op.drop_table('booking')
    op.drop_table('seat')
    op.drop_table('screening')
    op.drop_table('user')
    op.drop_table('screen')
    op.drop_table('movie')
    # ### end Alembic commands ###
