"""empty message

Revision ID: 389bed1618d6
Revises: 59e7e0dbd47c
Create Date: 2021-04-12 22:48:00.271893

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '389bed1618d6'
down_revision = '59e7e0dbd47c'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Postcode', sa.String(length=25), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('card', schema=None) as batch_op:
        batch_op.drop_column('Postcode')

    # ### end Alembic commands ###
