"""Added Card table

Revision ID: 88602d3e9a37
Revises: ca108459f2aa
Create Date: 2021-03-15 00:48:02.328638

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '88602d3e9a37'
down_revision = 'ca108459f2aa'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('card',
    sa.Column('CardID', sa.Integer(), nullable=False),
    sa.Column('UserID', sa.Integer(), nullable=True),
    sa.Column('CardNo', sa.String(length=25), nullable=True),
    sa.Column('Name', sa.String(length=50), nullable=True),
    sa.Column('CVV', sa.String(length=5), nullable=True),
    sa.Column('Expiry', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['UserID'], ['user.UserID'], ),
    sa.PrimaryKeyConstraint('CardID')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('card')
    # ### end Alembic commands ###
