"""Adde sd seat code and removed username

Revision ID: ca108459f2aa
Revises: bff0c6c28db6
Create Date: 2021-03-03 13:44:14.285271

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ca108459f2aa'
down_revision = 'bff0c6c28db6'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.add_column(sa.Column('code', sa.String(length=5), nullable=True))

    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('Username')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('Username', sa.VARCHAR(length=20), nullable=True))

    with op.batch_alter_table('seat', schema=None) as batch_op:
        batch_op.drop_column('code')

    # ### end Alembic commands ###
